### ISSUE TITLE
copr-cli and infrastructure as code

### ISSUE THREAD

**Issue by jfhbrook** [fedora-copr/copr#2767]
Hello,

Something I yearn for with `copr-cli` is the ability to take a declarative specification (yaml? json?) and call the correct REST methods to create or update as appropriate.

I think the gold standard for this kind of thing is `kubectl apply`. In fact, I thought about prototyping this with go and kubernetes. But you could do something similar with PyYAML. You don't necessarily have to copy Kubernetes wholesalee - the important thing is that I can specify the properties I want a COPR resource (`project`, `package``) to have, commit them to git, and use a script to synchronize with COPR. For bonus points, hook it up to GitHub Actions.

I got a little too creative with bash to prototype some of these ideas. It's not worth sharing - that said,  you can get pretty far by calling a `get` (or `HEAD` with a web client) and switching between `create` and `edit` accordingly. But the DSL bits are challenging in bash :sweat_smile: and I'm starting to think what makes the most sense is getting it in upstream. It looks like the `apply` verb is free - hopefully it would be relatively straightforward to wedge this in?

Chances are good I'd write another cut of this eventually. I'm definitely interested in contributing upstream though! So I figured I'd at least start the conversation and see how people feel about this sort of thing.

**Comment by jfhbrook** [comment]
For what it's worth, I dusted off the bash protptype and finished it. You can see it here:

https://github.com/jfhbrook/public/tree/main/coprctl

It's nowhere near complete, but it demonstrates the idea and is good enough for my immediate needs. :sweat_smile:

**Comment by FrostyX** [comment]
Hello @jfhbrook,
thank you for the RFE and for kicking off the implementation.

It is an interesting idea and it might be helpful for some people. I know projects, such as Packit and Fedora Review Service (and others that I've seen throughout the years) that want to make sure a Copr project exists and is configured in some way before submitting a new build. They usually do that by trying to create a new project and catching the exception that it already exists.

If I understand your goals correctly, this is one of the things that you are trying to solve?

I have no idea how much those projects would be interested in using `coprctl` or consider it overkill for their situation and rather be interested in small API tweaks such as #2140. You'll have to find out.

Anyway, we would be happy to promote `coprctl` in the [documentation](https://docs.pagure.org/copr.copr), share any related blogposts on the Copr homepage, and so on. But I am afraid we don't have enough resources to work on the implementation ourselves.

> However, long term I think the right answer might be to add this sort of functionality directly to copr-cli. I made an issue here:

Personally, I would keep those tools separate. What is your opinion @praiskup?

There is a technical issue - `coprctl` is written in Bash, so it would have to be implemented from scratch in Python. But even then I think that from user experience, it makes sense to keep those tools separate.

> coprctl apply -f ./copr.yml

I wanted to try `coprctl` but, I am getting

```
$ coprctl apply -f /tmp/copr.yml 
Error: open /home/jkadlcik/.config/coprctl/config.yml: no such file or directory
```

Not sure if it is a bug or an error on my side :-)

And a side note - I am not invested in the YAML format, please use what is the most suitable for you. But I looked at the example YAML and thought that ansible-like format might also be good, e.g.

```yaml
- name: Create a Copr project
  project: name="do-not-delete-me-2" description="a test COPR"

- name: Create a PyPI package
  package:
    name: "python3-pyee"
    project: "do-not-delete-me-2"
    source:
      type: pypi
      spec_generator: pyp2spec
      python_versions:
        - 3

- name: Create a RubyGems package
  package:
    name: "rubygem-t"
    project: "do-not-delete-me-2"
    source: type=rubygems gem="t"
```
